### ISSUE TITLE
Bug:  官网下载报错 公众号打不开

### ISSUE THREAD

**Issue by silent-night-no-trace** [CodePhiliaX/Chat2DB#1508]
### Chat2DB Version

3.2.4

### Describe the bug

<img width="848" alt="image" src="https://github.com/user-attachments/assets/4114b375-0a8d-4e07-bdcc-8e6ed44010f4">

这玩意有人维护么 ，官网下载都不行啊

关注二维码就算了，你这个二维码都出不来

**Comment by miahemu** [comment]
你好，你这边是想下载哪个版本的？windows还是mac？

**Comment by tmlx1990** [comment]
> ### Chat2DB Version
> 3.2.4
> 
> ### Describe the bug
> <img alt="image" width="848" src="https://private-user-images.githubusercontent.com/21052733/358111844-4114b375-0a8d-4e07-bdcc-8e6ed44010f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM3MTIzMTgsIm5iZiI6MTcyMzcxMjAxOCwicGF0aCI6Ii8yMTA1MjczMy8zNTgxMTE4NDQtNDExNGIzNzUtMGE4ZC00ZTA3LWJkY2MtOGU2ZWQ0NDAxMGY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDA4NTMzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzY2FmZTEyMjgwZDA0M2I2ZTU2NTE5MDZmYjcwZTRhZDE3ZjVmYjAxMzU1YjQzMGQ1Y2Q3MzhhNTE4ZGU0ZTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RwoDtOxWZW8Pe6ZKpKgu95bj2OXUJoMkVPjmi7ZPXEo">
> 这玩意有人维护么 ，官网下载都不行啊
> 
> 关注二维码就算了，你这个二维码都出不来

开源版在这里下载：https://github.com/chat2db/Chat2DB/releases
pro版这里：https://chat2db-ai.com/zh-CN/download
