### ISSUE TITLE
优化: 如何使用 pro 版本的代码，以及 docker 镜像是否支持 pro版本

### ISSUE THREAD

**Issue by sudo-keke** [CodePhiliaX/Chat2DB#1517]

**Comment by sudo-keke** [comment]
1、clone 下来代码本地运行后，发现是普通版的3.2.4，缺少了 redis 数据源，同时界面 UI 也不同，不知道 pro 版本的代码是否是公开的。

2、在dockerhub 上找到的镜像只有普通版的3.2.4，后续是否考虑支持 pro 版本的新镜像
![image](https://github.com/user-attachments/assets/b7183d8b-5ea4-41bd-9180-042a4469b5c1)

3、当我想在无桌面版的 Linux 上运行 web 版本，（可以通过浏览器访问链接的方式）是否支持这种方式，（目前只能通过 docker 的方式运行）

**Comment by JerryFan626** [comment]
Pro 版本是商业版本，非开源版本
Pro 版本支持 Web 端直接访问，[https://app.chat2db-ai.com](https://app.chat2db-ai.com)
