### ISSUE TITLE
建议: Provide README for Chat2DB's Docker Image

### ISSUE THREAD

**Issue by linghengqian** [CodePhiliaX/Chat2DB#1519]
- I noticed that there is a Docker Image for Chat2DB at https://github.com/CodePhiliaX/Chat2DB/tree/main/docker , but it seems to only have unit tests and no corresponding README file.
- I searched the site's documentation on Google and didn't see any instructions for Docker Image. This uses `docker site:https://docs.chat2db.ai/docs/`.
- ![image](https://github.com/user-attachments/assets/74320c5d-21ec-4119-a5b3-60016b8dae63)
- Am I missing something?

**Comment by tmlx1990** [comment]
You can use the official docker image at the following address:
https://github.com/CodePhiliaX/Chat2DB/wiki/Chat2DB-%E6%BA%90%E7%A0%81%E9%83%A8%E7%BD%B2%E5%92%8CDocker%E9%83%A8%E7%BD%B2

**Comment by linghengqian** [comment]
> You can use the official docker image at the following address: https://github.com/CodePhiliaX/Chat2DB/wiki/Chat2DB-%E6%BA%90%E7%A0%81%E9%83%A8%E7%BD%B2%E5%92%8CDocker%E9%83%A8%E7%BD%B2

- Thanks for the clarification.
