### ISSUE TITLE
Bug: Unable to start Chat2DB via Docker Engine

### ISSUE THREAD

**Issue by linghengqian** [CodePhiliaX/Chat2DB#1521]
### Chat2DB Version

3.2.4

### Describe the bug

- I cannot start Chat2DB through Docker Engine. Just execute the following command under Ubuntu 22.04.4 WSL,
```shell
docker run -d chat2db/chat2db:3.2.4 -p 10824:10824 --name chat2db
```
- Attempting to access `http://localhost:10824/` directly results in access being denied.
- ![image](https://github.com/user-attachments/assets/3d90a39c-1a8a-49fc-abd0-d7f7443f42a7)
- I don't see any errors in the logs from the Docker Container. Is there some documentation I missed?
- ![image](https://github.com/user-attachments/assets/2763e9f1-60de-454a-8b09-c64f439d0da9)

**Comment by tmlx1990** [comment]
换3.1.22的镜像试试。

**Comment by linghengqian** [comment]
> 换3.1.22的镜像试试。

- Even using `docker run -d chat2db/chat2db:3.1.22 -p 10824:10824 --name chat2db`, accessing `localhost:10824` still doesn't work. What am I missing?
- ![image](https://github.com/user-attachments/assets/8852a6f0-520d-459b-9782-2470308a826e)

**Comment by miahemu** [comment]
try this：
https://docs.chat2db.ai/docs/question/private-deployment

**Comment by linghengqian** [comment]
> try this： https://docs.chat2db.ai/docs/question/private-deployment

- @miahemu I started chat2db with the following command, but still could not open `http://localhost:10824/` normally.

```shell
docker run -itd chat2db/chat2db:3.2.4 -p 10824:10824 --name chat2db
```
- ![image](https://github.com/user-attachments/assets/97549e88-4e7d-47ea-bdf7-a67d57f7544b)
- ![image](https://github.com/user-attachments/assets/b55f5ab5-8569-4466-9950-c420c70d4d58)

**Comment by Fayord** [comment]
I'm also face the same problem and I try to see any ERROR log in the docker run process and it has no ERROR to trace this problem it look like it run correctly !?
anyone success to run it local?

**Comment by test16553** [comment]
How should we solve this problem?

**Comment by test16553** [comment]
> ### Chat2DB Version
> 3.2.4
> 
> ### Describe the bug
> * I cannot start Chat2DB through Docker Engine. Just execute the following command under Ubuntu 22.04.4 WSL,
> 
> ```shell
> docker run -d chat2db/chat2db:3.2.4 -p 10824:10824 --name chat2db
> ```
> 
> * Attempting to access `http://localhost:10824/` directly results in access being denied.
> * ![image](https://private-user-images.githubusercontent.com/20187731/363272622-3d90a39c-1a8a-49fc-abd0-d7f7443f42a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1MDE1NDUsIm5iZiI6MTczMTUwMTI0NSwicGF0aCI6Ii8yMDE4NzczMS8zNjMyNzI2MjItM2Q5MGEzOWMtMWE4YS00OWZjLWFiZDAtZDdmNzQ0M2Y0MmE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDEyMzQwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4NzAzMGUxODEyOWNmYTc4OWJlM2I1NGNiMTdhMzFjMTU4OTA2Nzk1Y2IwZDM4ZDJiY2M5MDU2M2Q1NDBjNGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.oAveZmUmAXGuaLWiqsRKQoaqM7VOpYgRWxi-uFyhwJo)
> * I don't see any errors in the logs from the Docker Container. Is there some documentation I missed?
> * ![image](https://private-user-images.githubusercontent.com/20187731/363272835-2763e9f1-60de-454a-8b09-c64f439d0da9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1MDE1NDUsIm5iZiI6MTczMTUwMTI0NSwicGF0aCI6Ii8yMDE4NzczMS8zNjMyNzI4MzUtMjc2M2U5ZjEtNjBkZS00NTRhLThiMDktYzY0ZjQzOWQwZGE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDEyMzQwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEwZDFlZmVmY2JkZjAzNDY3NmRmZjViMzU0NDc3YTQ0NWFiZDA4ODRjNzc4OWQ4ODdiYzc0NDMwMzljYzlmZDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0hhPUVvwK-14UI3Xldeq5KdCpQGVsMdOcGi-jowfwFY)

启动容器的时候将镜像名称放到映射端口后就好了

**Comment by linghengqian** [comment]
- @test16553 Thanks, this was originally a documentation issue. The command `docker run -d chat2db/chat2db:3.2.4 -p 10824:10824 --name chat2db` I remember originally came from somewhere in the documentation at https://chat2db-ai.com/ .
- I have used `docker run -p 10824:10824 --name chat2db -d chat2db/chat2db:3.2.4` to complete the test. I can log in to `localhost:10824` using the `chat2db` account and `chat2db` password.
- ![image](https://github.com/user-attachments/assets/a53d7735-fd67-4d4f-aaf8-62991852f3dd)
- There seems to be no need to keep the current issue open.
