### ISSUE TITLE
建议: 推出离线版本

### ISSUE THREAD

**Issue by a2089886864hao** [CodePhiliaX/Chat2DB#1526]
什么时候可以推出离线版本，急急急

**Comment by a2089886864hao** [comment]
居然真会有反馈呀，好的，狠狠期待住了



---- 回复的原邮件 ----
| 发件人 | Xin ***@***.***> |
| 日期 | 2024年09月15日 21:44 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [CodePhiliaX/Chat2DB] 建议: 推出离线版本 (Issue #1526) |

已经在规划了。后续会上的。

**Comment by Chat2DB-Pro** [comment]
离线版关注Ch2db的公众号，10月16号正式发布
