### ISSUE TITLE
Bug: 无法连接Sqlserver

### ISSUE THREAD

**Issue by FanJun1999** [CodePhiliaX/Chat2DB#1533]
### Chat2DB Version

Chat2DB Pro2.5.7

### Describe the bug

连接Sqlserver时出现报错，日志在附件里，使用的驱动是mssql-jdbc-6.2.2.jre8.jar
[log.txt](https://github.com/user-attachments/files/17127161/log.txt)
![PixPin_2024-09-25_15-38-07](https://github.com/user-attachments/assets/0e68bda9-c5fe-4ccd-8853-14cd473986bf)

**Comment by FanJun1999** [comment]
补一张数据源配置
![PixPin_2024-09-25_15-43-51](https://github.com/user-attachments/assets/2b1af52f-8799-4f50-9850-5a013f0a7212)

**Comment by Chat2DB-Pro** [comment]
使用默认驱动jre17的驱动
