### ISSUE TITLE
建议: tinyint类型展示时候展示数字，而不是bool值

### ISSUE THREAD

**Issue by Tristin-C** [CodePhiliaX/Chat2DB#1536]
tinyint类型的字段，有-1 0 1 2 3 4 等状态，目前全是bool值，不能直观的查看具体阶段。

**Comment by tmlx1990** [comment]
mysql在链接的高级设置里增加这个设置tinyInt1isBit=false

**Comment by Tristin-C** [comment]
> tinyInt1isBit=false

🙏谢谢大佬。

**Comment by Tristin-C** [comment]
@tmlx1990 请问还有其他配置吗，在哪里可以看到

**Comment by tmlx1990** [comment]
> @tmlx1990 请问还有其他配置吗，在哪里可以看到

什么其他配置？只要这样加了，应该就能看到真实值了。
![image](https://github.com/user-attachments/assets/3da5df7d-267d-4c6a-81c6-5c7faeb771da)

**Comment by Tristin-C** [comment]
> > @tmlx1990 请问还有其他配置吗，在哪里可以看到
> 
> 什么其他配置？只要这样加了，应该就能看到真实值了。 ![image](https://private-user-images.githubusercontent.com/5753992/375648987-3da5df7d-267d-4c6a-81c6-5c7faeb771da.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2MjkwMTksIm5iZiI6MTcyODYyODcxOSwicGF0aCI6Ii81NzUzOTkyLzM3NTY0ODk4Ny0zZGE1ZGY3ZC0yNjdkLTRjNmEtODFjNi01YzdmYWViNzcxZGEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMTFUMDYzODM5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZGQyNjNmMjliYTUwZGM2ZDgwYTBiMjMzYjdlNmU3NzVmNmIzOWYzYzhhZTBlZGFiMDk5Y2JmZWRhNDA0YmRlMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.emqsA6NViCgtikbrIUPOvh5RJywAEEeujYc5xP8Mifg)

嗯嗯。能看到了
