### ISSUE TITLE
建议: 开源的目标是商业版吗，现在都没有明确的开源版下载地址

### ISSUE THREAD

**Issue by JIPINGBABA** [CodePhiliaX/Chat2DB#1562]

**Comment by Chat2DB-Pro** [comment]
github上 release下载啊 ，不知道怎么用github？？？

**Comment by JIPINGBABA** [comment]
github下载链接直接跳转到这里，在和我开玩笑吗，抛开MIT协议不谈，你们是2.0开源协议里最没有诚意的



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年11月08日 16:38 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [CodePhiliaX/Chat2DB] 建议: 开源的目标是商业版吗，现在都没有明确的开源版下载地址 (Issue #1562) |

Closed #1562 as completed.

**Comment by tmlx1990** [comment]
这里都可以下载啊 
<img width="1174" alt="image" src="https://github.com/user-attachments/assets/71bf5b36-d63b-41b0-ac40-49aa966f93ac">

**Comment by JIPINGBABA** [comment]
好吧，感谢



---- 回复的原邮件 ----
| 发件人 | Xin ***@***.***> |
| 日期 | 2024年11月09日 11:41 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [CodePhiliaX/Chat2DB] 建议: 开源的目标是商业版吗，现在都没有明确的开源版下载地址 (Issue #1562) |

这里都可以下载啊
image.png (view on web)
