### ISSUE TITLE
优化: 这货不对版吧。别人广告108永久版本，点进来永久版本799

### ISSUE THREAD

**Issue by Ruling95** [CodePhiliaX/Chat2DB#1612]
广告位
https://mp.weixin.qq.com/s/FtHHCM02ifYhOkqKJJCzZg
![image](https://github.com/user-attachments/assets/926e7d01-dae3-4bab-bb5e-2dabe9e906d5)

实际价格：
![image](https://github.com/user-attachments/assets/488a7a37-dcc3-4ace-94a0-d8e0214bd96e)

根本不是一回事嘛。

**Comment by tmlx1990** [comment]
> 广告位 https://mp.weixin.qq.com/s/FtHHCM02ifYhOkqKJJCzZg ![image](https://private-user-images.githubusercontent.com/49261119/398821865-926e7d01-dae3-4bab-bb5e-2dabe9e906d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyNjIzMTksIm5iZiI6MTczNTI2MjAxOSwicGF0aCI6Ii80OTI2MTExOS8zOTg4MjE4NjUtOTI2ZTdkMDEtZGFlMy00YmFiLWJiNWUtMmRhYmU5ZTkwNmQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI3VDAxMTMzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQwZjBiMWZhZmRlZGM5MTBmZDMyOTcyNDA2YWRlZjNjOGY3MTg0NmRmZWE5MGI0ODAyNTA1NDNiYThkYzMxZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ziTjWN_yV6JkU4EK4k6Yj32UGBOpfwfrHKr0sHhBvH4)
> 
> 实际价格： ![image](https://private-user-images.githubusercontent.com/49261119/398821925-488a7a37-dcc3-4ace-94a0-d8e0214bd96e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyNjIzMTksIm5iZiI6MTczNTI2MjAxOSwicGF0aCI6Ii80OTI2MTExOS8zOTg4MjE5MjUtNDg4YTdhMzctZGNjMy00YWNlLTk0YTAtZDhlMDIxNGJkOTZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI3VDAxMTMzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ0MzU5NjJjMTMzNTY5YzU0YmZmZGEzNDBkMjM5ZWMzZDg4OWUwYzJmOGZjNTZiMDA3NTgwY2I5YTg1NWFhZmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.h58QP3Cf7Hxo_Z_x9s7brfSgV2xCpM1rOYfq0IeUSlk)
> 
> 根本不是一回事嘛。

您好，对方公众号使用的是以前刚发布Local版时候的价格，没有查看最新售价。价格以官网为准。购买时可以输入优惠码666666
<img width="1286" alt="image" src="https://github.com/user-attachments/assets/9182556e-de4d-4c1b-b2cd-97e70ff9e1ba" />
